name: Bun Basic Action
description: A basic GitHub Action using Bun
author: Jeff Njoroge <jeff283>

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun ci
      shell: bash

    - name: Build the app
      run: bun run build
      shell: bash
